name = "LayoutPointers"
uuid = "10f19ff3-798f-405d-979b-55457f8fc047"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "0.1.5"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"
SIMDTypes = "94e857df-77ce-4151-89e5-788b33177be4"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
ArrayInterface = "3.1.24"
ManualMemory = "0.1.6"
SIMDTypes = "0.1"
Static = "0.3, 0.4, 0.5"
julia = "1.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ArrayInterface", "Test"]
